- IdeIntegration/Bindings/ILBindingRegistryBuilder.cs
- VsIntegration/Bindings/Discovery/VsBindingRegistryBuilder.cs
This pull request differs from the last pull request as it removes the csproj changes that made the project compilable under VS 2012.
> Binding inheritance

- IdeIntegration/Generator/RemoteAppDomainTestGeneratorFactory.cs
The config is generated by https://github.com/techtalk/SpecFlow/pull/554
> Load plugincompability.config to Generator AppDomain if the file exists in the generator folder

- VsIntegration/AutoComplete/IntellisensePresenter/CompletionSessionView.xaml
- VsIntegration/AutoComplete/IntellisensePresenter/CompletionSessionView.xaml.cs
IntelliSense popup is now scrollable.
> #481: Add scrollbars to intelliSense

- IdeIntegration/Generator/IdeSingleFileGenerator.cs
- IdeIntegration/Generator/RemoteAppDomainTestGeneratorFactory.cs
- IdeIntegration/TechTalk.SpecFlow.IdeIntegration.csproj
- ItemTemplates/TechTalk.SpecFlow.VsIntegration.ItemTemplates.csproj
- SpecFlow.VisualStudio.2013.sln
- SpecFlow.VisualStudio.2015.sln
- SpecFlow.VisualStudio.2017.sln
- TechTalk.SpecFlow.RemoteAppDomain/Info.cs
- TechTalk.SpecFlow.RemoteAppDomain/Properties/AssemblyInfo.cs
- TechTalk.SpecFlow.RemoteAppDomain/RemoteAppDomainResolver.cs
- TechTalk.SpecFlow.RemoteAppDomain/TechTalk.SpecFlow.RemoteAppDomain.csproj
- TechTalk.SpecFlow.RemoteAppDomain/packages.config
- UnitTests/IdeIntegration.UnitTests/TechTalk.SpecFlow.IdeIntegration.UnitTests.csproj
- VsIntegration/15.0.source.extension.vsixmanifest
- VsIntegration/TechTalk.SpecFlow.VsIntegration.csproj
to fix https://github.com/techtalk/SpecFlow/issues/857
> Loading generator assembly without changing ApplicationBase folder

- VsIntegration/TechTalk.SpecFlow.VsIntegration.csproj
resolves https://github.com/techtalk/SpecFlow/issues/1241
> fix references for VS2013

- IdeIntegration/Generator/OutOfProcess/OutOfProcessExecutor.cs
- IdeIntegration/Services/FileSystem.cs
- IdeIntegration/Services/IFileSystem.cs
- IdeIntegration/TechTalk.SpecFlow.IdeIntegration.csproj
- UnitTests/IdeIntegration.UnitTests/FileSystemTests.cs
- UnitTests/IdeIntegration.UnitTests/TechTalk.SpecFlow.IdeIntegration.UnitTests.csproj
resolves https://github.com/techtalk/SpecFlow/issues/1378
> handle exchange path without ending backslash

- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.cs
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.fs
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.vb
For Issue #1314 https://github.com/techtalk/SpecFlow/issues/1314
Is this ok, or should I squash to a single commit?
> Issue #1314: Updated SpecFlow Step Definitions in ItemTemplates

- VsIntegration/SpecFlowPackage.cs
Just some typos in comments in the SpecFlowPackage.cs.
> Fix some typos

- IdeIntegration/Generator/OutOfProcess/OutOfProcessTestGenerator.cs
- IdeIntegration/Options/IntegrationOptions.cs
- VsIntegration/14.0.source.extension.vsixmanifest
- VsIntegration/15.0.source.extension.vsixmanifest
- VsIntegration/Options/IntegrationOptionsProvider.cs
- VsIntegration/Options/OptionsPageGeneral.cs
- VsIntegration/SingleFileGenerator/CodeGeneratorRegistrationWithFileExtensionAttribute.cs
- VsIntegration/SingleFileGenerator/CustomToolSwitch.cs
- VsIntegration/SingleFileGenerator/SpecFlowSingleFileGenerator.cs
- VsIntegration/TechTalk.SpecFlow.VsIntegration.csproj
- VsIntegration/specflow.pkgdef
could resolve https://github.com/techtalk/SpecFlow/issues/1311 a little bit
> Dynamic disable of custom tool SpecFlowSingleFileGenerator

- IdeIntegration/Generator/IdeSingleFileGenerator.cs
- IdeIntegration/Generator/ProjectInfo.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/SingleFileGenerator/SpecFlowSingleFileGeneratorBase.cs
- changelog.txt
see https://github.com/techtalk/SpecFlow/issues/1487
> remove generator fallback

- TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/CompletionCommandFilter.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/AutoComplete/IntellisensePresenter/CompletionSessionView.xaml
- TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/CompletionWithImage.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Utils/StringLiteralHelper.cs
Exact copy if this PR, but without the conflicts. 
https://github.com/techtalk/SpecFlow.VisualStudio/pull/43
> Add columns names to autocomplete suggestions

- TechTalk.SpecFlow.VSIXShared/LanguageService/GherkinBufferServiceManager.cs
Resolves https://github.com/techtalk/SpecFlow/issues/863
> Fix language service crash after viewing opened feature file diff in Visual Studio

- README.md
Used Community as this is OSS! :)
> Docs: Added Start external program for VS2019

- changelog.txt
> Update changelog.txt for #79

- TechTalk.SpecFlow.VSIXShared/LanguageService/GherkinBufferServiceManager.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/GherkinLanguageService.cs
- changelog.txt
> Fix ObjectDisposedException when opening and closing a second window for the same feature file

- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.cs
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.vb
- SpecFlowStarterProjectTemplate/Steps/CalculatorStepDefinitions.cs
Adjust the SpecFlow project template and the SpecFlow Step Definition item template to be compliant with coding guidelines (naming).
> Adjust SpecFlow project/item template (#8076)

- ItemTemplates/SpecFlowFeature/SpecFlowFeature1.feature
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.cs
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.fs
- ItemTemplates/SpecFlowStepDefinition/SpecFlowStepDefinition1.vb
- SpecFlowStarterProjectTemplate/Features/Calculator.feature
- SpecFlowStarterProjectTemplate/Steps/CalculatorStepDefinitions.cs
Improvement of the default specflow example
Now, the new default specflow example is:
```
Scenario: Add two numbers
Given the first number is 50
And the second number is 70
When the two numbers are added
Then the result should be 120
```
> Improvement of the default specflow example

- ProjectTemplateWizard/ProjectTemplateWizard.csproj
- ProjectTemplateWizard/UserInputControl.xaml
- ProjectTemplateWizard/WizardImplementation.cs
- SpecFlowStarterProjectTemplate/SpecFlowStarterProjectTemplate.vstemplate
- Remove include for key file which had already been deleted.
Background information: We use the already existing specflow.snk key file for signing the ProjectTemplateWizard assembly. That is why that new key file became redundant and was removed.
- Use the latest full framework to date (.NET Framework 4.8)
- Fix issue of not finding step definitions
> Improvements and a bug fix regarding the SpecFlow project template (#8076)

- SpecFlowStarterProjectTemplate/Features/Calculator.feature
- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
Update project template to support LivingDoc Generator
- Update dependencies to accommodate the needs of LivingDoc Generator
- Add the SpecFlow+LivingDoc Generator Plugin to the project template
- Add some examples to the existing Calculator feature file in the project template that demonstrate some features of LivingDoc:
- text formatting
- embedding external images
- adding links
- internal linking between features
> Update project template to support LivingDoc Generator (#8929)

- ProjectTemplateWizard/UserInputControl.xaml
- ProjectTemplateWizard/UserInputDialog.cs
- ProjectTemplateWizard/WizardImplementation.cs
- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Add FluentAssertions to project wizard

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Update specflow package versions

- .marketplace/overview.md
- .marketplace/publishManifest.2017.json
- .marketplace/publishManifest.json
- VsIntegration/source.extension.vsixmanifest
- VsIntegration2015/source.extension.vsixmanifest
- VsIntegration2017/source.extension.vsixmanifest
- changelog.txt
- publish.marketplace.ps1
> Marketplace release automation

- VsIntegration/source.extension.vsixmanifest
- VsIntegration2017/source.extension.vsixmanifest
- changelog.txt
Add prerequisite for the SpecFlow project wizard.
- The new project wizards needs additional components to generate a new SpecFlow project into the solution
- If the required components are missing (e.g. only the VS shell is installed without any workload) the wizard fails with an error message
`Operation could not be completed. The project file '*path to your new project csproj*' cannot be migrated. See the migration report for details.`
> Add prerequisite for the SpecFlow project wizard

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Update wizard package versions

- ProjectTemplateWizard/UserInputControl.xaml
- changelog.txt
Fix styling issues in the Project Template Wizard:
- make labels fully visible
- apply correct styling to checkbox
> Fix styling issues in the Project Template Wizard - #2203

- ProjectTemplateWizard/UserInputControl.xaml
- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Dot net 5 support in the Project Template Wizard

- ItemTemplates/SpecFlowFeature/SpecFlowFeature1.feature
- SpecFlowStarterProjectTemplate/Features/Calculator.feature
> Update the feature file templates

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Update nunit in the create project wizard

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Update package versions to 3.6

- ProjectTemplateWizard/UserInputControl.xaml
- changelog.txt
> add missing supported .NET implementations to the combo box

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Update package versions to 3.7

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Update LivingDocPlugin in project template

- TechTalk.SpecFlow.VsIntegration.Implementation/DefaultDependencyProvider.cs
> Use external Default OS Browser for Notifications

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Update package versions to point to the latest ones

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Update nunit package reference

- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
- changelog.txt
> Update MSTest package references in project templates

- TechTalk.SpecFlow.VsIntegration.Implementation/EditorCommands/FormatTableCommand.cs
> Remove \r character after format if the file did not have it before

- IdeIntegration/Analytics/Events/NotificationAnalyticsEvents.cs
- IdeIntegration/Analytics/IAnalyticsTransmitter.cs
- IdeIntegration/Install/ExternalBrowserNotificationService.cs
- IdeIntegration/Install/IBrowserNotificationService.cs
- IdeIntegration/Install/InstallServices.cs
- TechTalk.SpecFlow.VSIXShared/SpecFlowPackage.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Analytics/AnalyticsTransmitter.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Analytics/AppInsightsEventConverter.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/DefaultDependencyProvider.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Install/VsBrowserNotificationService.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Notifications/NotificationData.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Notifications/NotificationDataStore.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Notifications/NotificationInfoBar.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Notifications/NotificationInfoBarFactory.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/Notifications/NotificationService.cs
- TechTalk.SpecFlow.VsIntegration.Implementation/TechTalk.SpecFlow.VsIntegration.Implementation.csproj
- UnitTests/VsIntegration.Implementation.UnitTests/InstallServicesTests.cs
- changelog.txt
> Add notifications support

- .gitignore
- GitExtensions.settings
- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Update package versions in ProjectTemplate #198

- ProjectTemplateWizard/UserInputControl.xaml
- SpecFlowStarterProjectTemplate/ProjectTemplate.csproj
> Remove the SpecFlow+ Runner from the Project Wizard
