SpecFlowOSS/SpecFlow.VisualStudio

VsIntegration/TestRunner/ReSharper6TestRunnerGateway.cs
Assuming that the only difference is the Run/Debug Context commands. Uses existing code to figure out what Resharper version is installed.
So far tested on VS2013 and Resharper 8.2, busy upgrading to 9 to double check.
=> Updated Resharper Gateway/loader to support multiple versions of Resharper 

VsIntegration/Utils/VsxHelper.cs
Please see: https://github.com/techtalk/SpecFlow/issues/726
This isn't the most ideal solution, but it does work as a workaround until the Roslyn team fixes the issue.
=> COMException when navigating to step definition

VsIntegration/TechTalk.SpecFlow.VsIntegration.2013.csproj, VsIntegration/TechTalk.SpecFlow.VsIntegration.2015.csproj, VsIntegration/TechTalk.SpecFlow.VsIntegration.2017.csproj
According to readme.vs, every VS version requires corresponding SDK, but actually they all are currently dependent on VS2013 SDK.  
It is fixed, and both 2015 and 2017 solutions are dependent on corresponding SDK.
=> Update VS references for 2015 and 2017 solutions.

VsIntegration/AutoComplete/CompletionCommandFilter.cs
Fixes the issue, when intellisense suggestions set is unfiltered, if step text is not empty, but intellisense was invoked using Ctrl+Space
=> Fix intellisense showing unfiltered suggestions in case of ctrl+space

VsIntegration/AutoComplete/IntellisensePresenter/CompletionSessionView.xaml, VsIntegration/AutoComplete/IntellisensePresenter/CompletionSessionView.xaml.cs
Currently in intellisense dialog in grid with listbox has height="Auto". However, this property does not limit size of listbox. It means that list listbox virtualization is not used, as well as its scroll viewer. And in case of huge amount of steps it takes TOO long for dialog to appear (on our project - up to 10 seconds).
It is fixed by using height="*" instead.
Before (red border - boundaries of listbox, height - something about 28000 px):
=> Fix IntelliSense dialog low performance

TechTalk.SpecFlow.VsIntegration.Common.targets, VsIntegration/TestRunner/ReSharper6TestRunnerGateway.cs
Adds right-click context support for Resharper 2017.1 (v108); the alias for 'ReSharper_UnitTest**Run**Context' [was changed](https://www.jetbrains.com/help/resharper/2017.1/Reference__Keyboard_Shortcuts.html) to 'ReSharper_UnitTest**RunFrom**Context'.
Currently running SpecFlow via right-click context with ReSharper 2017.1 will throw the exception 
```ReSharper6TestRunnerGateway: test tool error: System.Runtime.InteropServices.COMException (0x80004005): Command "ReSharper.ReSharper_UnitTestRunContext" is not valid.```
And display the modal error 'Object reference not set to an instance of an object.'
=> Fix for right-click context with Resharper 2017.1

VsIntegration/Bindings/Discovery/VsBindingRegistryBuilder.cs, VsIntegration/SingleFileGenerator/SpecFlowSingleFileGenerator.cs
When using Specflow in a test project which uses any of the new project model elements introduced in VS2017 such as multi-targeting, nuget package references, .NET standard projects, .NET core projects, etc the SpecFlowSingleFileGenerator will not run feature files contained within the project.
Furthermore, due to a bug in visual studio, CodeClass2.Parts is not always populated for these projects. This was preventing detection of already existant step bindings which was in turn causing the syntax highlighting in the feature files to appear as if they did not have step bindings (purple).
There is still one outstanding issue I noted with these projects, which is that even with the two issues above fixed, you still must alter the .cs file containing the step bindings in order for the proper …
=> SpecFlowSingleFileGenerator does not run for feature files contained in projects of type "9A19103F-16F7-4668-BE54-9A1E7A4F7556"

IdeIntegration/TechTalk.SpecFlow.IdeIntegration.csproj, IdeIntegration/TechTalk.SpecFlow.IdeIntegration.csproj.DotSettings, ItemTemplates/TechTalk.SpecFlow.VsIntegration.ItemTemplates.csproj, ItemTemplates/TechTalk.SpecFlow.VsIntegration.ItemTemplates.csproj.DotSettings, UnitTests/IdeIntegration.UnitTests/TechTalk.SpecFlow.IdeIntegration.UnitTests.csproj, UnitTests/IdeIntegration.UnitTests/TechTalk.SpecFlow.IdeIntegration.UnitTests.csproj.DotSettings, VsIntegration/TechTalk.SpecFlow.VsIntegration.csproj, VsIntegration/TechTalk.SpecFlow.VsIntegration.csproj.DotSettings
Since the highest supported C# language version of Visual Studio 2013 is 5.0, setting the maximum C# version to 5.0 should improve writing code for multiple Visual Studio versions.
When set to "Default" and working with VS 2017, the IDE automatically uses C# 7.x.
It does not warn you about not supported code constructs (like String Concatenation) in older VS versions.
If the C# version is set to 5.0, the IDE can already tell you to not use newer constructs at writing time.
=> Changed all projects' C# version to 5.0

IdeIntegration/Generator/OutOfProcess/OutOfProcessExecutor.cs
The issue is actually '1234' / not lazy-typing: https://github.com/techtalk/SpecFlow/issues/1234
The temp file path will end in a backslash, which causes the command line generator to improperly quote the output directory. 
--
Confirmed / fixed the issue with code behind files failing to generate. 
The issue was that the Path.GetTempPath() call returns a string ending in a backslash. This doesn't bode well in the subsequent call to the CommandLineParser when it generates the command line parameters for the call to the *.CodeBehindGenerator.exe
=> Issue 1234

TechTalk.SpecFlow.VisualStudio.CodeBehindGenerator/App.config
Relates to the following issue: https://github.com/techtalk/SpecFlow/issues/1337
=> Updated app.config to ensure that assembly can be loaded for the code behind generator

IdeIntegration/Options/IntegrationOptions.cs, VsIntegration/AutoComplete/CustomCompletionSet.cs, VsIntegration/AutoComplete/GherkinStepCompletionSource.cs, VsIntegration/AutoComplete/HierarchicalCompletionSet.cs, VsIntegration/Options/IntegrationOptionsProvider.cs, VsIntegration/Options/OptionsPageGeneral.cs
Problem is that when steps are highly reused, intellisense dialog becomes too messy, since per each step template 10-20 step instances are suggested. It makes much harder to find required step.
Here how it looks for our project:
This PR adds ability to limit quantity of step instances per each step template.
=> Add ability to limit maximum amount of step instances intellisense suggestions

TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/GherkinProcessingScheduler.cs, TechTalk.SpecFlow.VsIntegration.Implementation/LanguageService/IdleTaskProcessingQueue.cs
- Allow regular checking whether thread should be cancelled
- Name thread for easier debugging/diagnostics
- Set time limit to wait for thread to finish when disposing
Fixes https://github.com/techtalk/SpecFlow/issues/456
=> Attempt to avoid dispose deadlock

build.ps1
Fixes https://github.com/techtalk/SpecFlow/issues/1632
=> Only set AppInsightsInstrumentationKey on command-line if it has a value

TechTalk.SpecFlow.VSIXShared/Options/IntegrationOptionsProvider.cs, TechTalk.SpecFlow.VsIntegration.Implementation/Options/OptionDefaultValues.cs, TechTalk.SpecFlow.VsIntegration.Implementation/Options/OptionsPageGeneral.cs
This is done by separating registry registration of the single file generator and the VS extension option preference.
Registering the single file generator in the registry is still necessary I believe, see [Registering Single File Generators](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators?view=vs-2019) over at Microsoft Docs. 
I also changed the default setting to `false`, which seems only logical for a legacy setting.
Resolves https://github.com/techtalk/SpecFlow/issues/1584.
I found it quite hard to test, but it seems to be working alright. Could you do an extensive test as well? Thanks!
=> Fix reset of legacy 'Enable SpecFlowSingleFileGeneratorCustomTool' setting

TechTalk.SpecFlow.VsIntegration.Implementation/TechTalk.SpecFlow.VsIntegration.Implementation.csproj
We should use the InstrumentationKey of an Application Insights which is accessible for everyone.
I already created a resource group @ Azure - we should use that for **testing** (instead of David's resource group) 
Details can be found in OneNote.
=> Use instrumentation key of the "common" resource group for testing

TechTalk.SpecFlow.VSIXShared/SpecFlowSingleFileGenerator.cs
Because the Custom Tool is registered via attributes, it enabled at the first startup after installing or updating the VS extension. It was disabled the launches after the first start.
Removing the attributes fixes this unintended behavior.
=> remove registration of CustomTool via attributes

TechTalk.SpecFlow.VsIntegration.Implementation/UI/GenerateStepDefinitionSkeletonForm.cs
First it will try to find the folder <projectfolder>/StepDefinitions (current code)
If not found, then use the directory where the .feature file lives
fixes https://github.com/SpecFlowOSS/SpecFlow/issues/1638
Tested it locally with VS2019 multiple times. 
Todo
=> Changed default directory for generating steps file to the same directory as the .feature file

README.md
And clicking on them will redirect to the correct VS marketplace page
preview: 
live preview: https://github.com/304NotModified/SpecFlow.VisualStudio/blob/patch-2/README.md
=> Added installations badges to readme

SpecFlowStarterProjectTemplate/ProjectTemplate.csproj, TechTalk.SpecFlow.VsIntegration.Implementation/DefaultDependencyProvider.cs, TechTalk.SpecFlow.VsIntegration.Implementation/EditorCommands/IStepNameReplacer.cs, TechTalk.SpecFlow.VsIntegration.Implementation/EditorCommands/RenameCommand.cs, TechTalk.SpecFlow.VsIntegration.Implementation/EditorCommands/StepNameReplacer.cs, UnitTests/VsIntegration.Implementation.UnitTests/StepNameReplacerTests.cs
Renaming a step (with parameters) in a feature file caused the parameters in the step names to be replaced to the regex, so the former values got overwritten.
Only steps with different regex than `(.*)` were affected.
Examples of bad behaviour:
- RegEx with numbers (shown in the previous gif):
Step name: `the first number is 50`
Binding regex: `the first number is (\d+)`
If you rename this Step to `the number is (\d+)`, then all occurrences in the feature files were changed to `the number is (\d+)
`
- RegEx values as a string:
Step name: `The car should be painted yellow`
Binding regex: `The car should be painted (blue|yellow|green)`
If you rename this Step to `The car is (blue|yellow|green)`, then all occurrences in the feature files were changed to 
`The car is (blue|yellow|green)` …
=> Fix: Renaming a step should not change the parameters

IdeIntegration/Configuration/JsonConfig/JsonConfigurationLoader.cs, ItemTemplates/SpecFlowJson/specflow.json, changelog.txt
Currently if we add a `specflow.json` file through Item templates, it generates an invalid configuration:
```
{
"bindingCulture":
{
"language" :"en-us"
},
"language":
{
"feature": "en-us"
}
}
```
`bindingCulture` element have `name` attribute, not `language` (also written in [docs](https://docs.specflow.org/projects/specflow/en/latest/Installation/Configuration.html#bindingculture)).
=> Fix specflow.json template to generate a valid configuration

azure-pipelines.yml
WhiteSource Bolt is not reporting since December 2019. As I found out the problem was that we are using an older version of the WS Bolt build task. After updating it to the latest (version 20), it works again.
=> Fix WhiteSource Bolt reporting

TechTalk.SpecFlow.VsIntegration.Implementation/Utils/VsxHelper.cs, TechTalk.SpecFlow.VsIntegration.Implementation/VsSpecFlowConfigurationReader.cs
Fix bug issue #192
The App.config file may not be in the project items but it can be defined in the csproj file in the PropertyGroup->AppConfig element
- [ X] Bug fix (non-breaking change which fixes an issue).
=> 192-Inspect csproj to find the appconfig location
